export interface ProjectTask {
  area: string;
  items: string[];
}

export interface Project {
  slug: string;
  title: string;
  location: string;
  community?: string;
  budget: string;
  year: number;
  service: "kitchen" | "bathroom" | "restoration" | "full-home" | "basements" | "age-in-place";
  categories: string[];
  tags: string[];
  hero: string;
  beforePhotos?: string[];
  gallery: string[];
  excerpt: string;
  description: string;
  tasks: ProjectTask[];
  outcome: string;
}

export const projects: Project[] = [
  {
    slug: "whole-home-restoration-marietta",
    title: "Whole Home Restoration — Marietta",
    location: "Marietta, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "full-home",
    categories: ["Full Home", "Featured"],
    tags: ["Kitchen", "Flooring", "Paint", "Cabinets", "Restoration", "Modern"],
    hero: "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-03.jpg",
    beforePhotos: ["/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-before-01.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-before-02.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-before-03.jpg"],
    gallery: ["/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-01.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-02.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-03.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-04.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-05.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-06.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-07.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-08.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-09.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-10.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-11.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-12.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-13.jpg", "/images/projects/whole-home-restoration-marietta/whole-home-restoration-marietta-ga-14.jpg"],
    excerpt: "A complete whole-home restoration in Marietta — updated kitchen, refinished hardwood floors, fresh paint, and modernized finishes throughout.",
    description: "This Marietta homeowner needed a top-to-bottom refresh before listing. TopFlight Builders handled the full scope — new kitchen cabinetry and countertops, refinished hardwood floors across the main level, updated fixtures, and interior paint throughout. The result is a home that shows like new.",
    tasks: [
      { area: "Kitchen", items: ["New shaker cabinetry with updated hardware", "Quartz countertops and tile backsplash", "Appliance coordination and installation"] },
      { area: "Flooring", items: ["Hardwood floor refinishing throughout main level", "Transition and threshold work"] },
      { area: "Interior", items: ["Full interior repaint — walls, trim, and ceilings", "Updated lighting fixtures", "Door hardware replacement"] },
    ],
    outcome: "A Marietta home transformed from dated to market-ready — cleaner, brighter, and built to impress buyers from the first showing.",
  },
  {
    slug: "whole-home-restoration-atlanta",
    title: "Whole Home Restoration — Atlanta",
    location: "Atlanta, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "full-home",
    categories: ["Full Home", "Featured"],
    tags: ["Bathrooms", "Flooring", "Paint", "Vanity", "Modern", "Gold Fixtures"],
    hero: "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-01.jpg",
    beforePhotos: ["/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-before-01.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-before-02.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-before-03.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-before-04.jpg"],
    gallery: ["/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-01.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-02.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-03.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-04.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-05.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-06.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-07.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-08.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-09.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-10.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-11.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-12.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-13.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-14.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-15.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-16.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-17.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-18.jpg", "/images/projects/whole-home-restoration-atlanta/whole-home-restoration-atlanta-ga-19.jpg"],
    excerpt: "A whole-home restoration in Atlanta featuring a stunning navy double vanity, marble-look tile, hardwood floors, and bold accent walls throughout.",
    description: "This Atlanta home received a comprehensive restoration covering multiple bathrooms, flooring, and interior updates. The standout feature is the master bath — a navy double vanity with quartz countertops, gold fixtures, and crystal sconces. Every room was brought up to date with intentional design and quality finishes.",
    tasks: [
      { area: "Master Bathroom", items: ["Navy double vanity with quartz countertop", "Gold hardware and crystal sconce lighting", "Marble-look porcelain tile flooring", "New mirrors and plumbing fixtures"] },
      { area: "Flooring", items: ["Hardwood flooring refinished throughout", "Tile work in wet areas"] },
      { area: "Interior", items: ["Bold accent wall paint throughout living areas", "Updated trim, doors, and hardware", "New lighting fixtures"] },
    ],
    outcome: "An Atlanta home completely transformed — the master bath alone is a showstopper, and the updated finishes throughout make every room feel intentional.",
  },
  {
    slug: "kitchen-remodel-canton",
    title: "Kitchen Remodel — Canton",
    location: "Canton, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "kitchen",
    categories: ["Kitchens", "Featured"],
    tags: ["Cabinets", "Island", "Quartz", "Pendant Lights", "Dark Hardwood", "Modern Farmhouse"],
    hero: "/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-01.jpg",
    gallery: ["/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-01.jpg", "/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-02.jpg", "/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-03.jpg", "/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-04.jpg", "/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-05.jpg", "/images/projects/kitchen-remodel-canton/kitchen-remodel-canton-ga-06.jpg"],
    excerpt: "A modern farmhouse kitchen in Canton — white shaker cabinets, a two-tone island, quartz countertops, and dark hardwood floors.",
    description: "This Canton kitchen remodel delivered a dramatic transformation. White shaker upper cabinets contrast with a slate-blue island featuring a waterfall quartz top. Industrial pendant lights, a pro-style faucet, and dark hardwood floors complete the modern farmhouse look the homeowners envisioned.",
    tasks: [
      { area: "Cabinetry", items: ["Full cabinet removal and replacement", "White shaker uppers and lowers", "Contrasting slate-blue island with built-in seating"] },
      { area: "Surfaces", items: ["Quartz countertops with waterfall island edge", "Tile backsplash installation", "Dark hardwood flooring"] },
      { area: "Fixtures & Lighting", items: ["Industrial pendant lights over island", "Pro-style pull-down faucet", "Under-cabinet LED lighting", "Appliance coordination"] },
    ],
    outcome: "A Canton kitchen that makes a statement — the two-tone island and pendant lighting combo turned a dated space into the heart of the home.",
  },
  {
    slug: "kitchen-remodel-roswell",
    title: "Kitchen Remodel — Roswell",
    location: "Roswell, GA",
    budget: "$40,000",
    year: 2026,
    service: "kitchen",
    categories: ["Kitchens"],
    tags: ["Load Bearing Wall", "Open Concept", "Quartz", "Recessed Lighting", "Under-Cabinet Lighting", "Backsplash"],
    hero: "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-02.jpg",
    beforePhotos: ["/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-before-01.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-before-02.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-before-03.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-before-04.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-before-05.jpg"],
    gallery: ["/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-01.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-02.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-03.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-04.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-05.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-06.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-07.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-08.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-09.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-10.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-11.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-12.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-13.jpg", "/images/projects/kitchen-remodel-roswell/kitchen-remodel-roswell-ga-14.jpg"],
    excerpt: "A full kitchen remodel in Roswell — load-bearing wall removed and beams installed for open concept, quartz countertops, backsplash tile, and a comprehensive electrical upgrade including under-cabinet lighting.",
    description: "This Roswell kitchen remodel started with the most complex move — removing a load-bearing wall and installing new beams to create a fully open concept layout. TopFlight Builders then installed new cabinetry, shelving, and all finish trim. The sink plumbing was relocated, a refrigerator line was added, and all new fixtures and appliances were installed. A full electrical upgrade followed: recessed lighting, replaced and added light fixtures, relocated receptacles and switches, two circuit relocations, and under-cabinet lighting. Quartz countertops and backsplash tile completed the kitchen, and drywall and painting were finished in the kitchen and pantry areas.",
    tasks: [
      { area: "Carpentry", items: ["Removed load-bearing wall and installed new beams for open concept layout", "Installed new cabinets, shelving, and all finish trim work"] },
      { area: "Plumbing", items: ["Relocated sink plumbing", "Added refrigerator line", "Installed all new fixtures and appliances"] },
      { area: "Electrical", items: ["Replaced and added light fixtures", "Added recessed lighting throughout", "Relocated electrical receptacles and switches", "Relocated two circuits", "Under-cabinet lighting installation"] },
      { area: "Countertops", items: ["Quartz countertops installed"] },
      { area: "Tile", items: ["Backsplash tile installation"] },
      { area: "Drywall & Painting", items: ["Drywall and painting in kitchen and pantry areas"] },
    ],
    outcome: "A Roswell kitchen transformed by structural work few contractors will take on — the load-bearing wall removal created an open concept that changed how the entire floor plan lives.",
  },
  {
    slug: "bathroom-remodel-east-cobb",
    title: "Bathroom Remodel — East Cobb",
    location: "East Cobb, GA",
    budget: "$31,000",
    year: 2026,
    service: "bathroom",
    categories: ["Bathrooms", "Featured"],
    tags: ["Frameless Glass", "Freestanding Tub", "Gold Fixtures", "Spa", "Sage Tile", "Natural Light", "Quartz"],
    hero: "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-01.jpg",
    beforePhotos: ["/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-before-01.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-before-02.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-before-03.jpg"],
    gallery: ["/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-01.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-02.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-03.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-04.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-05.jpg", "/images/projects/bathroom-remodel-east-cobb/bathroom-remodel-east-cobb-ga-06.jpg"],
    excerpt: "A spa-inspired master bath in East Cobb — freestanding soaking tub, frameless glass shower, quartz countertops, new vanity cabinets, and a full electrical update.",
    description: "This East Cobb master bathroom is a full retreat. The entire bathroom was demoed and rebuilt — including new vanity cabinets and a completely redesigned shower and tub configuration. A large frameless glass shower features tile walls and pan with custom glass doors, while the freestanding soaking tub anchors the opposite side. Quartz countertops and porcelain sinks complete the double vanity. Electrical was updated with a new ceiling light and exhaust fan, and the bathroom was drywalled and painted to finish.",
    tasks: [
      { area: "Carpentry & Demo", items: ["Full demo of existing shower, tub, and tile", "Framed new openings for shower configuration", "Installed new vanity cabinets", "Installed finish trim throughout"] },
      { area: "Plumbing", items: ["Relocated water lines and drains", "Installed new shower and tub fixtures", "Freestanding tub installation", "Installed new toilet"] },
      { area: "Electrical", items: ["Relocated receptacles", "Added exhaust fan", "Added ceiling light"] },
      { area: "Tile", items: ["Tile on bathroom floor", "Tile on shower walls and shower pan"] },
      { area: "Shower Glass", items: ["Custom shower glass door installation"] },
      { area: "Drywall & Painting", items: ["New drywall installed as needed", "Painted bathroom"] },
      { area: "Countertops & Sinks", items: ["Quartz countertops", "Porcelain sink installation"] },
    ],
    outcome: "An East Cobb master bath that feels like a five-star spa — the sage tile and gold hardware combination is one of our favorite builds this year.",
  },
  {
    slug: "bathroom-remodel-woodstock",
    title: "Bathroom Remodel — Woodstock",
    location: "Woodstock, GA",
    budget: "$22,000",
    year: 2026,
    service: "bathroom",
    categories: ["Bathrooms", "Featured"],
    tags: ["Marble Look", "Frameless Glass", "Large Format Tile", "LVP Flooring", "Shower Glass", "Luxury"],
    hero: "/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-01.jpg",
    beforePhotos: ["/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-before-01.jpg", "/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-before-02.jpg"],
    gallery: ["/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-01.jpg", "/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-02.jpg", "/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-03.jpg", "/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-04.jpg", "/images/projects/bathroom-remodel-woodstock/bathroom-remodel-woodstock-ga-05.jpg"],
    excerpt: "A full bathroom remodel in Woodstock — new shower configuration, large format wall tile, LVP flooring, shower surround glass, and new tub and toilet.",
    description: "This Woodstock bathroom was fully gutted and rebuilt from the ground up. The previous shower, tub, and tile were completely demolished, and the space was reframed for a new shower configuration. Water lines and drains were relocated, a new tub and toilet were installed, and the damaged flange was repaired. Large format tile was installed on the bathroom and shower walls, LVP flooring was laid throughout, and shower surround glass completed the space.",
    tasks: [
      { area: "Carpentry & Demo", items: ["Full demo of existing shower, tub, and tile", "Framed new openings for shower configuration", "Installed finish trim throughout"] },
      { area: "Plumbing", items: ["Relocated water lines and drains", "Installed new shower and tub fixtures", "New tub installation", "Installed new toilet and repaired damaged flange"] },
      { area: "Tile", items: ["Large format tile on bathroom walls", "Large format tile on shower walls"] },
      { area: "Flooring", items: ["LVP flooring installed throughout bathroom"] },
      { area: "Shower Glass", items: ["Shower surround glass installation"] },
    ],
    outcome: "A Woodstock bathroom completely rebuilt — clean layout, large format tile, and LVP flooring create a fresh, modern space that's built to last.",
  },
  {
    slug: "kitchen-laundry-remodel-east-cobb",
    title: "Kitchen & Laundry Room Remodel — East Cobb",
    location: "East Cobb, GA",
    budget: "Contact for Pricing",
    year: 2025,
    service: "kitchen",
    categories: ["Kitchens", "Featured"],
    tags: ["Cabinets", "Countertops", "Laundry Room", "Tile", "Modern"],
    hero: "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-09.jpg",
    beforePhotos: ["/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-before-01.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-before-02.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-before-03.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-before-04.jpg"],
    gallery: ["/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-01.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-02.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-03.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-04.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-05.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-06.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-07.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-08.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-09.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-10.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-11.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-12.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-13.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-14.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-15.jpg", "/images/projects/kitchen-laundry-east-cobb/kitchen-laundry-remodel-east-cobb-ga-16.jpg"],
    excerpt: "Full kitchen and laundry room remodel in East Cobb — new cabinetry, countertops, tile, and a completely refreshed laundry space.",
    description: "This East Cobb homeowner wanted a comprehensive update to both their kitchen and laundry room. TopFlight Builders handled every detail of both spaces — from cabinet demolition to final finish work — delivering a cohesive, modern result throughout.",
    tasks: [
      {
        area: "Kitchen",
        items: ["Removed existing cabinetry and appliances", "Installed new shaker cabinetry with soft-close hardware", "Quartz countertops and tile backsplash", "Updated lighting and fixtures"],
      },
      {
        area: "Laundry Room",
        items: ["New cabinetry for storage", "Tile flooring installation", "Updated utility connections and fixtures"],
      },
    ],
    outcome: "Both spaces transformed to match the homeowner's vision — clean, functional, and built to last.",
  },
  {
    slug: "whole-home-renovation-east-cobb",
    title: "Whole-Home Renovation — East Cobb",
    location: "East Cobb, GA",
    budget: "Contact for Pricing",
    year: 2025,
    service: "full-home",
    categories: ["Full Home", "Featured"],
    tags: ["Kitchen", "Bathrooms", "Flooring", "Paint", "Modern"],
    hero: "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-02.jpg",
    beforePhotos: ["/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-before-01.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-before-02.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-before-03.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-before-04.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-before-05.jpg"],
    gallery: ["/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-01.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-02.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-03.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-04.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-05.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-06.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-07.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-08.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-09.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-10.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-11.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-12.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-13.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-14.jpg", "/images/projects/whole-home-east-cobb/whole-home-renovation-east-cobb-ga-15.jpg"],
    excerpt: "A top-to-bottom whole-home renovation in East Cobb covering kitchen, bathrooms, flooring, and full interior updates.",
    description: "This East Cobb whole-home renovation gave the property a complete refresh from the ground up. TopFlight Builders coordinated all trades across multiple rooms simultaneously, delivering a cohesive finished product that transformed the entire home.",
    tasks: [
      {
        area: "Kitchen & Bathrooms",
        items: ["Full kitchen cabinet and countertop replacement", "Bathroom tile, vanity, and fixture updates throughout"],
      },
      {
        area: "Flooring & Finishes",
        items: ["New flooring installed throughout all living areas", "Full interior repaint — walls, ceilings, and trim", "Updated lighting fixtures sitewide"],
      },
    ],
    outcome: "A complete home transformation completed on schedule. The homeowners moved into a space that felt entirely brand new.",
  },
  {
    slug: "bathroom-remodel-brookhaven",
    title: "Bathroom Remodel — Brookhaven",
    location: "Brookhaven, GA",
    budget: "$49,000",
    year: 2025,
    service: "bathroom",
    categories: ["Bathrooms", "Featured"],
    tags: ["Open Concept", "Crown Molding", "Freestanding Tub", "Quartzite", "Custom Shower Glass", "Tile"],
    hero: "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-08.jpg",
    beforePhotos: ["/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-before-01.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-before-02.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-before-03.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-before-04.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-before-05.jpg"],
    gallery: ["/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-01.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-02.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-03.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-04.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-05.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-06.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-07.jpg", "/images/projects/bathroom-brookhaven/bathroom-remodel-brookhaven-ga-08.jpg"],
    excerpt: "A high-end Brookhaven bathroom remodel — non-load-bearing walls removed for open concept layout, quartzite countertops, freestanding tub, custom shower glass, and crown molding throughout.",
    description: "This Brookhaven bathroom is one of our most comprehensive remodels — the homeowners wanted to fundamentally change the layout before touching a single finish. TopFlight Builders removed non-load-bearing walls to create an open concept bathroom layout, framed new walls and decorative openings, and installed finish trim and crown molding throughout. The shower, tub, and all tile were fully demolished and rebuilt with tile on the floor, shower walls, and shower pan. Water lines and drains were relocated, a freestanding tub and new toilet were installed, and custom shower glass doors were added. All electrical within the walls was relocated to accommodate the new layout, ceiling fixtures were replaced, and the vanity light was updated. The bathroom was drywalled, painted, and the bathroom cabinets were painted. Quartzite countertops and porcelain sinks complete the vanity.",
    tasks: [
      { area: "Carpentry & Demo", items: ["Full demo of existing shower, tub, and tile", "Removed non-load-bearing walls to create open concept layout", "Framed new walls and decorative openings", "Installed finish trim and crown molding throughout"] },
      { area: "Plumbing", items: ["Relocated water lines and drains", "Installed new shower and tub fixtures", "Freestanding tub installation", "Installed new toilet"] },
      { area: "Electrical", items: ["Relocated receptacles and switches from demolished walls", "Relocated existing lighting for new layout", "Replaced ceiling fixtures", "Replaced vanity light fixture"] },
      { area: "Tile", items: ["Tile on bathroom floor", "Tile on shower walls and shower pan"] },
      { area: "Shower Glass", items: ["Custom shower glass door installation"] },
      { area: "Drywall & Painting", items: ["New drywall installed as needed", "Painted bathroom", "Painted bathroom cabinets"] },
      { area: "Countertops & Sinks", items: ["Quartzite countertops", "Porcelain sink installation"] },
    ],
    outcome: "A Brookhaven bathroom transformed at the structural level — the open concept layout change made this project exceptional, and the quartzite countertops and crown molding brought it to a standard that matches the quality of the home.",
  },
  {
    slug: "home-addition-atlanta",
    title: "Home Addition — Atlanta",
    location: "Atlanta, GA",
    budget: "Contact for Pricing",
    year: 2025,
    service: "basements",
    categories: ["Basements & Additions", "Featured"],
    tags: ["Addition", "Framing", "Drywall", "Flooring", "Exterior"],
    hero: "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-13.jpg",
    beforePhotos: ["/images/projects/home-addition-atlanta/home-addition-atlanta-ga-before-01.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-before-02.jpg"],
    gallery: ["/images/projects/home-addition-atlanta/home-addition-atlanta-ga-01.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-02.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-03.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-04.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-05.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-06.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-07.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-08.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-09.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-10.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-11.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-12.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-13.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-14.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-15.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-16.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-17.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-18.jpg", "/images/projects/home-addition-atlanta/home-addition-atlanta-ga-19.jpg"],
    excerpt: "A full home addition in Atlanta — expanding the footprint with new framing, roofing, and finished interior space.",
    description: "This Atlanta homeowner needed more space and chose to expand rather than move. TopFlight Builders designed and built a full home addition — handling everything from permits and foundation to framing, roofing, insulation, drywall, and finished interior.",
    tasks: [
      {
        area: "Structure",
        items: ["Foundation prep and framing", "Roof tie-in and exterior weatherproofing", "Window and door installation"],
      },
      {
        area: "Interior Finish",
        items: ["Insulation and drywall throughout", "Flooring to match existing home", "Paint, trim, and final finish work"],
      },
    ],
    outcome: "The addition seamlessly extended the home's living space, adding significant square footage and value.",
  },
  {
    slug: "bathroom-remodel-buckhead",
    title: "Bathroom Remodel — Buckhead",
    location: "Buckhead, GA",
    budget: "Contact for Pricing",
    year: 2025,
    service: "bathroom",
    categories: ["Bathrooms"],
    tags: ["Quartzite", "Freestanding Tub", "Custom Shower Glass", "Accent LED", "Concrete Demo", "Tile", "Luxury"],
    hero: "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-01.jpg",
    beforePhotos: ["/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-01.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-02.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-03.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-04.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-05.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-06.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-07.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-before-08.jpg"],
    gallery: ["/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-01.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-02.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-03.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-04.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-05.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-06.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-07.jpg", "/images/projects/bathroom-buckhead/bathroom-remodel-buckhead-ga-08.jpg"],
    excerpt: "A high-end Buckhead bathroom renovation — concrete removed to relocate drains, freestanding tub, custom shower glass, quartzite countertops, and accent LED lighting.",
    description: "This Buckhead bathroom renovation required breaking through concrete to relocate drains and water lines for the new layout — one of the more involved plumbing moves in a bathroom remodel. TopFlight Builders demolished the existing shower, tub, and tile, framed new walls and decorative openings, and rebuilt the entire bathroom to a high-end standard. A freestanding tub and new toilet were installed alongside custom shower glass doors. Quartzite countertops and porcelain sinks complete the vanity. All electrical within the walls was relocated for the new layout, ceiling and vanity fixtures were replaced, accent LED lighting was added, and the exhaust fan was relocated. The bathroom was drywalled and painted, including the bathroom cabinets.",
    tasks: [
      { area: "Carpentry & Demo", items: ["Full demo of existing shower, tub, and tile", "Framed new walls and decorative openings", "Installed finish trim throughout"] },
      { area: "Plumbing", items: ["Removed concrete and relocated drains and water lines for new layout", "Installed new shower and tub fixtures", "Freestanding tub installation", "Installed new toilet"] },
      { area: "Electrical", items: ["Relocated receptacles and switches for new layout", "Relocated existing lighting", "Replaced ceiling fixtures and vanity light", "Installed accent LED lighting", "Relocated exhaust fan"] },
      { area: "Tile", items: ["Tile on bathroom floor", "Tile on shower walls and shower pan"] },
      { area: "Shower Glass", items: ["Custom shower glass door installation"] },
      { area: "Drywall & Painting", items: ["New drywall installed as needed", "Painted bathroom and bathroom cabinets"] },
      { area: "Countertops & Sinks", items: ["Quartzite countertops", "Porcelain sink installation"] },
    ],
    outcome: "A high-end Buckhead bathroom built on the most demanding technical foundation — concrete removal for drain relocation, done right, with luxury finishes throughout.",
  },
  {
    slug: "basement-finishing-east-cobb",
    title: "Basement Finishing — East Cobb",
    location: "East Cobb, GA",
    budget: "Contact for Pricing",
    year: 2025,
    service: "basements",
    categories: ["Basements & Additions", "Featured"],
    tags: ["Basement", "Drywall", "LVP Flooring", "Lighting", "Entertainment"],
    hero: "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-01.jpg",
    beforePhotos: ["/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-before-01.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-before-02.jpg"],
    gallery: ["/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-01.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-02.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-03.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-04.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-05.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-06.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-07.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-08.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-09.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-10.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-11.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-12.jpg", "/images/projects/basement-east-cobb/basement-finishing-east-cobb-ga-13.jpg"],
    excerpt: "An unfinished East Cobb basement converted into a fully finished living space — framing, drywall, flooring, and lighting throughout.",
    description: "This East Cobb homeowner had an unfinished basement they wanted to turn into usable living space. TopFlight Builders handled the full build-out from framing to final finish — creating an open entertainment area with LVP flooring, recessed lighting, and clean drywall throughout.",
    tasks: [
      {
        area: "Framing & Rough-In",
        items: ["Interior wall framing throughout", "Electrical rough-in for lighting and outlets", "Egress window installation"],
      },
      {
        area: "Drywall & Finish",
        items: ["Insulation and drywall installation", "LVP flooring throughout", "Recessed lighting and trim work"],
      },
    ],
    outcome: "A completely finished basement that added significant usable square footage to the home.",
  },
  {
    slug: "bathroom-remodel-duluth",
    title: "Bathroom Remodel — Duluth",
    location: "Duluth, GA",
    budget: "$26,000",
    year: 2026,
    service: "bathroom",
    categories: ["Bathrooms"],
    tags: ["Freestanding Tub", "Custom Shower Glass", "Marble Countertops", "Tile", "Vanity Cabinets", "Modern"],
    hero: "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-01.jpg",
    beforePhotos: ["/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-before-01.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-before-02.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-before-03.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-before-04.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-before-05.jpg"],
    gallery: ["/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-01.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-02.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-03.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-04.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-05.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-06.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-07.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-08.jpg", "/images/projects/bathroom-remodel-duluth/bathroom-remodel-duluth-ga-09.jpg"],
    excerpt: "A full bathroom remodel in Duluth — freestanding tub, custom shower glass, tile on floor and shower walls, marble countertops, and new vanity cabinets.",
    description: "This Duluth homeowner wanted to fully transform their dated bathroom into a clean, modern space. TopFlight Builders demolished the existing shower, tub, and tile, then rebuilt the entire bathroom — framing a new shower configuration, installing new vanity cabinets, and relocating water lines and drains. A freestanding tub and new toilet were installed alongside custom shower glass doors. Marble countertops and porcelain sinks complete the vanity. Tile was installed on the bathroom floor, shower walls, and shower pan. Electrical was updated with a new exhaust fan and vanity light. The bathroom was drywalled and painted to finish.",
    tasks: [
      { area: "Carpentry & Demo", items: ["Full demo of existing shower, tub, and tile", "Framed new openings for shower configuration", "Installed new vanity cabinets", "Installed finish trim throughout"] },
      { area: "Plumbing", items: ["Relocated water lines and drains", "Installed new shower and tub fixtures", "Freestanding tub installation", "Installed new toilet"] },
      { area: "Electrical", items: ["Relocated receptacles", "Added exhaust fan", "Added vanity light"] },
      { area: "Tile", items: ["Tile on bathroom floor", "Tile on shower walls and shower pan"] },
      { area: "Shower Glass", items: ["Custom shower glass door installation"] },
      { area: "Drywall & Painting", items: ["New drywall installed as needed", "Painted bathroom"] },
      { area: "Countertops & Sinks", items: ["Marble countertops", "Porcelain sink installation"] },
    ],
    outcome: "A completely rebuilt Duluth bathroom — freestanding tub, marble countertops, and custom glass make it feel like a different home entirely.",
  },
  {
    slug: "kitchen-remodel-marietta",
    title: "Kitchen Remodel — Marietta",
    location: "Marietta, GA",
    budget: "$31,000",
    year: 2026,
    service: "kitchen",
    categories: ["Kitchens"],
    tags: ["Granite", "Open Concept", "Shaker Cabinets", "Recessed Lighting", "Tile Flooring", "Backsplash"],
    hero: "/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-01.jpg",
    beforePhotos: ["/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-before-01.jpg", "/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-before-02.jpg"],
    gallery: ["/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-01.jpg", "/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-02.jpg", "/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-03.jpg", "/images/projects/kitchen-remodel-marietta/kitchen-remodel-marietta-ga-04.jpg"],
    excerpt: "A complete kitchen remodel in Marietta — non-load-bearing wall removed, shaker cabinets, granite countertops, tile flooring and backsplash, and textured ceilings removed.",
    description: "This Marietta kitchen remodel transformed a closed-off, dated kitchen into a bright and open space. TopFlight Builders removed a non-load-bearing wall and closed off the previous entrance to improve the flow, then installed new shaker-style cabinets with all finish trim work. Granite countertops and a tile backsplash were added along with new tile flooring. Textured ceilings were removed and the drywall refinished throughout the kitchen area. The kitchen and hallway were painted, recessed lighting was added, receptacles and switches were relocated, and all new plumbing fixtures and appliances were installed including a new refrigerator line.",
    tasks: [
      { area: "Carpentry", items: ["Removed non-load-bearing wall to open the layout", "Closed off previous entrance", "Installed new shaker-style cabinets and all finish trim work"] },
      { area: "Electrical", items: ["Added recessed lighting throughout", "Relocated receptacles and switches"] },
      { area: "Plumbing", items: ["Added refrigerator line", "Installed all new plumbing fixtures and appliances"] },
      { area: "Countertops", items: ["Granite countertops installed"] },
      { area: "Tile", items: ["Tile flooring throughout kitchen", "Backsplash tile installation"] },
      { area: "Drywall & Painting", items: ["Removed textured ceilings and refinished drywall", "Painted kitchen and hallway areas"] },
    ],
    outcome: "A Marietta kitchen opened up and brought current — better layout, better light, and a clean modern finish from ceiling to floor.",
  },
  {
    slug: "kitchen-flooring-bathroom",
    title: "Kitchen, Flooring & Bathroom Remodel",
    location: "Greater Atlanta, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "full-home",
    categories: ["Full Home"],
    tags: ["Kitchen", "Bathroom", "Flooring", "LVP", "Tile", "Modern"],
    hero: "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-01.jpg",
    beforePhotos: ["/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-before-01.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-before-02.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-before-03.jpg"],
    gallery: ["/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-01.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-02.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-03.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-04.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-05.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-06.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-07.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-08.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-09.jpg", "/images/projects/kitchen-flooring-bathroom/kitchen-flooring-bathroom-remodel-marietta-ga-10.jpg"],
    excerpt: "A multi-room renovation covering kitchen, bathroom, and full flooring replacement throughout the home.",
    description: "This homeowner tackled multiple major updates at once — a full kitchen remodel, bathroom renovation, and new flooring throughout. TopFlight Builders coordinated all three scopes simultaneously, minimizing disruption and delivering a cohesive finished result across every room.",
    tasks: [
      {
        area: "Kitchen",
        items: ["New cabinetry and countertops", "Tile backsplash and updated fixtures", "Lighting and hardware refresh"],
      },
      {
        area: "Bathroom",
        items: ["Full bathroom gut and rebuild", "Custom tile shower and flooring", "New vanity and fixtures"],
      },
      {
        area: "Flooring",
        items: ["LVP flooring installed throughout all living areas", "Transitions and trim work completed", "Existing subfloor prepped and leveled"],
      },
    ],
    outcome: "Three major scopes completed under one contract — the homeowner got a fully refreshed home without juggling multiple contractors.",
  },
  {
    slug: "kitchen-deck-east-cobb",
    title: "Kitchen & Deck Remodel — East Cobb",
    location: "East Cobb, GA",
    budget: "$54,000",
    year: 2026,
    service: "kitchen",
    categories: ["Kitchens"],
    tags: ["Granite", "Open Concept", "Shaker Cabinets", "Electrical Panel", "Hardie Siding", "Tile", "Cast Iron Plumbing"],
    hero: "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-01.jpg",
    beforePhotos: ["/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-before-01.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-before-02.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-before-03.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-before-04.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-before-05.jpg"],
    gallery: ["/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-01.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-02.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-03.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-04.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-05.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-06.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-07.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-08.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-09.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-10.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-11.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-12.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-13.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-14.jpg", "/images/projects/kitchen-deck-east-cobb/kitchen-deck-remodel-east-cobb-ga-15.jpg"],
    excerpt: "A major kitchen remodel in East Cobb — open concept layout, shaker cabinets, granite countertops, full electrical panel replacement, cast iron pipe replacement, and Hardie siding on the exterior.",
    description: "This East Cobb project required significant structural and mechanical work before the finish work could begin. TopFlight Builders removed non-load-bearing walls and relocated the kitchen windows and back entrance door to create an open layout. Damaged cast iron piping was removed and replaced, and the kitchen sink plumbing was relocated. The electrical panel was replaced entirely, and the kitchen and dining room areas were rewired. With the rough work complete, new shaker-style cabinets and finish trim were installed, followed by granite countertops, tile throughout the kitchen footprint, and backsplash. New drywall was installed and finished throughout. Hardie siding was installed on the exterior.",
    tasks: [
      { area: "Carpentry", items: ["Removed non-load-bearing walls to open the layout", "Relocated kitchen windows and back entrance door"] },
      { area: "Cabinetry & Trim", items: ["Installed new shaker-style cabinets throughout", "Complete finish trim work"] },
      { area: "Plumbing", items: ["Removed and replaced damaged cast iron piping", "Relocated kitchen sink plumbing", "Installed all new plumbing fixtures"] },
      { area: "Electrical", items: ["Replaced damaged electrical panel", "Rewired kitchen and dining room areas"] },
      { area: "Countertops", items: ["Granite countertops installed"] },
      { area: "Tile", items: ["Tile installed throughout the new kitchen footprint", "Backsplash tile installation"] },
      { area: "Drywall", items: ["Installed and finished new drywall throughout"] },
      { area: "Exterior", items: ["Hardie siding installed on exterior"] },
    ],
    outcome: "A structurally improved and fully remodeled kitchen — from electrical panel to Hardie siding, this was a comprehensive renovation that tackled every layer of the home.",
  },
  {
    slug: "fallen-tree-remodel",
    title: "Fallen Tree Restoration — Marietta",
    location: "Marietta, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "restoration",
    categories: ["Restoration"],
    tags: ["Storm Damage", "Restoration", "Roofing", "Drywall", "Structural"],
    hero: "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-02.jpg",
    beforePhotos: ["/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-before-01.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-before-02.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-before-03.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-before-04.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-before-05.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-before-06.jpg"],
    gallery: ["/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-01.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-02.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-03.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-04.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-05.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-06.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-07.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-08.jpg", "/images/projects/fallen-tree-remodel/storm-damage-restoration-fallen-tree-marietta-ga-09.jpg"],
    excerpt: "Full storm damage restoration in Marietta after a fallen tree caused structural damage — from debris removal to finished interior.",
    description: "When a fallen tree caused significant damage to this Marietta home, the homeowners needed a contractor who could handle the entire scope — from emergency stabilization to full interior restoration. TopFlight Builders managed the complete project: structural repairs, roofing, exterior work, and finished interior rebuild.",
    tasks: [
      {
        area: "Structural & Exterior",
        items: ["Emergency tarping and site stabilization", "Structural framing repairs", "Roofing replacement in affected areas", "Exterior siding and trim restored"],
      },
      {
        area: "Interior Restoration",
        items: ["Drywall removal and replacement throughout damaged areas", "Insulation replaced", "Paint, trim, and finish work to match existing home"],
      },
    ],
    outcome: "The home was fully restored to pre-damage condition — structurally sound, finished throughout, and ready for the family to move back in.",
  },
  {
    slug: "restoration-fallen-tree-marietta",
    title: "Storm Damage Restoration — Marietta",
    location: "Marietta, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "restoration",
    categories: ["Restoration"],
    tags: ["Storm Damage", "Fallen Tree", "Structural Repair", "Roofing", "Interior Rebuild", "Marietta"],
    hero: "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-01.jpg",
    beforePhotos: [
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-before-01.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-before-02.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-before-03.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-before-04.jpg",
    ],
    gallery: [
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-01.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-02.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-03.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-04.jpg",
      "/images/projects/restoration-fallen-tree-marietta/restoration-fallen-tree-marietta-ga-05.jpg",
    ],
    excerpt: "Complete storm damage restoration in Marietta after a fallen tree caused major structural damage — full rebuild from framing to finished interior.",
    description: "A fallen tree caused serious structural damage to this Marietta home, requiring immediate stabilization and a full restoration from the outside in. TopFlight Builders handled the entire scope — structural framing repairs, roofing, and a complete interior rebuild — returning the home to better-than-original condition.",
    tasks: [
      {
        area: "Structural & Exterior",
        items: [
          "Emergency site stabilization and tarping",
          "Structural framing repairs in damaged areas",
          "Roof decking and shingle replacement",
          "Exterior trim and siding restored to match",
        ],
      },
      {
        area: "Interior Restoration",
        items: [
          "Full drywall removal and replacement in impacted areas",
          "Insulation replaced throughout",
          "Paint, trim, and finish work matched to existing home",
        ],
      },
    ],
    outcome: "A Marietta home rebuilt from the impact point out — structurally repaired, watertight, and finished throughout so the family could move back in.",
  },
  {
    slug: "fallen-tree-rebuild-stonecrest",
    title: "Fallen Tree Rebuild — Stonecrest",
    location: "Stonecrest, GA",
    budget: "Contact for Pricing",
    year: 2026,
    service: "restoration",
    categories: ["Restoration"],
    tags: ["Storm Damage", "Fallen Tree", "Major Rebuild", "Roofing", "Structural", "Stonecrest"],
    hero: "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-01.jpg",
    beforePhotos: [
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-01.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-02.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-03.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-04.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-05.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-06.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-07.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-08.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-before-09.jpg",
    ],
    gallery: [
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-01.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-02.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-03.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-04.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-05.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-06.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-07.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-08.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-09.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-10.jpg",
      "/images/projects/fallen-tree-rebuild-stonecrest/fallen-tree-rebuild-stonecrest-ga-11.jpg",
    ],
    excerpt: "A major fallen tree rebuild in Stonecrest — extensive structural damage repaired from foundation to roof, with full interior restoration throughout the impacted areas.",
    description: "This Stonecrest home sustained major damage when a large tree came through the structure, requiring a comprehensive rebuild that went well beyond surface repairs. TopFlight Builders managed the full scope — emergency stabilization, major structural framing work, a complete roofing rebuild, and interior restoration across every affected room. The before-and-after is one of our most dramatic transformations.",
    tasks: [
      {
        area: "Emergency & Structural",
        items: [
          "Emergency tarping and site stabilization",
          "Full structural assessment and permit coordination",
          "Major framing repairs across multiple areas of the home",
          "Roof decking, sheathing, and shingle replacement",
        ],
      },
      {
        area: "Exterior Rebuild",
        items: [
          "Exterior wall framing and sheathing repaired",
          "Siding and trim replaced to match existing",
          "Windows restored or replaced in impacted areas",
        ],
      },
      {
        area: "Interior Restoration",
        items: [
          "Drywall removal and full replacement throughout damaged rooms",
          "Insulation replaced in all impacted wall and ceiling cavities",
          "Paint, trim, and finish work matched throughout",
          "Flooring repairs in affected areas",
        ],
      },
    ],
    outcome: "A Stonecrest home rebuilt from the point of impact — structural, roofing, and interior all restored to move-in condition. One of our most comprehensive storm damage projects to date.",
  },
];

export function getProjectsByService(service: Project["service"]): Project[] {
  return projects.filter((p) => p.service === service);
}

export function getRelatedProjects(slug: string, service: Project["service"]): Project[] {
  return projects.filter((p) => p.slug !== slug && p.service === service).slice(0, 3);
}
